# Data Handling & Visualization 4 — Sorting, filtering, and summaries

**Digital Foundation for Chemical Engineers**  \nDuration: 60 minutes

## Today’s goal
Select relevant process records without losing the original data, sort observations, and calculate simple group-level summaries.

## 1. Start with a reproducible table (8 min)

Filtering in a spreadsheet is useful, but a Python command provides a visible record of the rule used. Work from a named raw dataset and store filtered views in new variables.

In [4]:
import pandas as pd

batches = pd.read_csv('https://raw.githubusercontent.com/mahekpise12-art/Module_5_6_Both/refs/heads/main/data/industrial_process_100.csv')
batches.head()

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
1,2026-01-05 09:00,B1001,R2,73.6,4.71,11.81,88.0,6.79,Bimal,OK
2,2026-01-05 10:00,B1001,R3,74.2,4.76,11.92,88.5,6.88,Chen,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
4,2026-01-05 12:00,B1001,R2,75.5,4.87,12.14,89.6,7.06,Asha,OK

## 2. Sorting makes patterns visible (12 min)

`sort_values()` orders a table by one or more columns. Use `ascending=False` for highest first. Sorting changes the display order, not the physical order in which events happened—keep a timestamp when time sequence matters.

In [5]:
highest_conversion = batches.sort_values('conversion_percent', ascending=False)
display(highest_conversion)

by_reactor_then_temperature = batches.sort_values(['reactor', 'temperature_c'])
display(by_reactor_then_temperature)

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
90,2026-01-09 02:00,B1010,R1,78.5,4.88,11.70,94.3,7.24,Chen,OK
64,2026-01-08 00:00,B1007,R2,82.7,5.23,11.81,94.0,6.79,Asha,OK
51,2026-01-07 11:00,B1006,R1,74.6,5.08,12.36,94.0,6.88,Deepa,OK
77,2026-01-08 13:00,B1008,R3,81.0,4.73,12.25,94.0,6.70,Bimal,OK
89,2026-01-09 01:00,B1009,R3,77.9,4.79,12.58,93.8,7.15,Bimal,OK
...,...,...,...,...,...,...,...,...,...,...
65,2026-01-08 01:00,B1007,R3,83.3,5.28,11.92,87.8,6.88,Bimal,OK
26,2026-01-06 10:00,B1003,R3,79.4,4.87,12.58,87.5,7.15,Chen,OK
13,2026-01-05 21:00,B1002,R2,81.1,4.76,12.14,87.5,7.24,Bimal,OK
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
39,2026-01-06 23:00,B1004,R1,76.9,5.02,12.03,87.5,7.06,Deepa,OK

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
18,2026-01-06 02:00,B1002,R1,73.6,5.04,11.70,90.1,7.06,Chen,OK
51,2026-01-07 11:00,B1006,R1,74.6,5.08,12.36,94.0,6.88,Deepa,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
36,2026-01-06 20:00,B1004,R1,75.0,4.86,11.70,92.7,6.79,Asha,OK
...,...,...,...,...,...,...,...,...,...,...
32,2026-01-06 16:00,B1004,R3,83.1,5.24,12.25,90.6,7.06,Asha,OK
65,2026-01-08 01:00,B1007,R3,83.3,5.28,11.92,87.8,6.88,Bimal,OK
98,2026-01-09 10:00,B1010,R3,83.5,5.32,12.58,91.7,6.70,Chen,OK
50,2026-01-07 10:00,B1006,R3,84.5,5.02,12.25,93.5,6.79,Chen,OK
83,2026-01-08 19:00,B1009,R3,84.7,5.06,11.92,90.7,7.24,Deepa,NOT TAKEN

**Try it (3 min):** Sort by temperature from high to low. Which batch is first?

**Challenge:** Sort by reactor and conversion descending within each reactor using a list for `ascending`.

## 3. Filtering with conditions (15 min)

A filter creates a Boolean condition for every row. Place that condition inside square brackets. Use `&` for AND and `|` for OR; enclose each comparison in parentheses.

In [9]:
r1_batches = batches[batches['reactor'] == 'R1']
low_conversion = batches[batches['conversion_percent'] < 90]
hot_and_low = batches[(batches['temperature_c'] > 85) & (batches['conversion_percent'] < 92)]

display(r1_batches)
display(low_conversion)
display(hot_and_low)

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
6,2026-01-05 14:00,B1001,R1,76.7,4.98,12.36,90.6,7.24,Chen,OK
9,2026-01-05 17:00,B1001,R1,78.6,5.15,11.70,92.2,6.88,Bimal,OK
12,2026-01-05 20:00,B1002,R1,80.4,4.71,12.03,93.7,7.15,Asha,OK
15,2026-01-05 23:00,B1002,R1,82.3,4.87,12.36,88.5,6.79,Deepa,OK
18,2026-01-06 02:00,B1002,R1,73.6,5.04,11.70,90.1,7.06,Chen,OK
21,2026-01-06 05:00,B1003,R1,75.5,5.20,12.03,91.7,6.70,Bimal,OK
24,2026-01-06 08:00,B1003,R1,77.3,4.76,12.36,93.2,6.97,Asha,OK
27,2026-01-06 11:00,B1003,R1,80.0,4.93,11.70,88.0,7.24,Deepa,OK
30,2026-01-06 14:00,B1004,R1,81.9,5.13,12.03,89.6,6.88,Chen,OK
33,2026-01-06 17:00,B1004,R1,83.7,4.69,12.36,91.1,7.15,Bimal,OK
36,2026-01-06 20:00,B1004,R1,75.0,4.86,11.70,92.7,6.79,Asha,OK
39,2026-01-06 23:00,B1004,R1,76.9,5.02,12.03,87.5,7.06,Deepa,OK
42,2026-01-07 02:00,B1005,R1,78.8,5.19,12.36,89.4,6.70,Chen,OK
45,2026-01-07 05:00,B1005,R1,80.6,4.75,11.70,90.9,6.97,Bimal,OK
48,2026-01-07 08:00,B1005,R1,82.5,4.91,12.03,92.5,7.24,Asha,OK
51,2026-01-07 11:00,B1006,R1,74.6,5.08,12.36,94.0,6.88,Deepa,OK
54,2026-01-07 14:00,B1006,R1,76.5,5.24,11.70,88.8,7.15,Chen,OK
57,2026-01-07 17:00,B1006,R1,78.3,4.80,12.03,90.4,6.79,Bimal,OK
60,2026-01-07 20:00,B1007,R1,80.2,5.01,12.36,92.0,7.06,Asha,OK
63,2026-01-07 23:00,B1007,R1,82.0,5.17,11.70,93.5,6.70,Deepa,OK
66,2026-01-08 02:00,B1007,R1,83.9,4.73,12.03,88.3,6.97,Chen,OK
69,2026-01-08 05:00,B1007,R1,75.2,4.90,12.36,89.9,7.24,Bimal,OK
72,2026-01-08 08:00,B1008,R1,77.1,5.06,11.70,91.4,6.88,Asha,OK
75,2026-01-08 11:00,B1008,R1,79.7,5.23,12.03,93.0,7.15,Deepa,OK
78,2026-01-08 14:00,B1008,R1,81.6,4.79,12.36,87.8,6.79,Chen,OK
81,2026-01-08 17:00,B1009,R1,83.5,4.95,11.70,89.7,7.06,Bimal,OK
84,2026-01-08 20:00,B1009,R1,85.3,5.12,12.03,91.2,6.70,Asha,OK
87,2026-01-08 23:00,B1009,R1,76.6,5.28,12.36,92.8,6.97,Deepa,OK
90,2026-01-09 02:00,B1010,R1,78.5,4.88,11.70,94.3,7.24,Chen,OK
93,2026-01-09 05:00,B1010,R1,80.4,5.05,12.03,89.1,6.88,Bimal,OK
96,2026-01-09 08:00,B1010,R1,82.2,5.21,12.36,90.7,7.15,Asha,OK
99,2026-01-09 11:00,B1010,R1,84.1,4.77,11.70,92.3,6.79,Deepa,OK

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
1,2026-01-05 09:00,B1001,R2,73.6,4.71,11.81,88.0,6.79,Bimal,OK
2,2026-01-05 10:00,B1001,R3,74.2,4.76,11.92,88.5,6.88,Chen,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
4,2026-01-05 12:00,B1001,R2,75.5,4.87,12.14,89.6,7.06,Asha,OK
13,2026-01-05 21:00,B1002,R2,81.1,4.76,12.14,87.5,7.24,Bimal,OK
14,2026-01-05 22:00,B1002,R3,81.7,4.82,12.25,88.0,6.70,Chen,OK
15,2026-01-05 23:00,B1002,R1,82.3,4.87,12.36,88.5,6.79,Deepa,OK
16,2026-01-06 00:00,B1002,R2,82.9,4.93,12.47,89.1,6.88,Asha,OK
17,2026-01-06 01:00,B1002,R3,73.0,4.98,12.58,89.6,6.97,Bimal,NOT TAKEN
26,2026-01-06 10:00,B1003,R3,79.4,4.87,12.58,87.5,7.15,Chen,OK
27,2026-01-06 11:00,B1003,R1,80.0,4.93,11.70,88.0,7.24,Deepa,OK
28,2026-01-06 12:00,B1003,R2,80.6,4.98,11.81,88.5,6.70,Asha,OK
29,2026-01-06 13:00,B1003,R3,81.2,5.04,11.92,89.1,6.79,Bimal,OK
30,2026-01-06 14:00,B1004,R1,81.9,5.13,12.03,89.6,6.88,Chen,OK
39,2026-01-06 23:00,B1004,R1,76.9,5.02,12.03,87.5,7.06,Deepa,OK
40,2026-01-07 00:00,B1005,R2,77.5,5.08,12.14,88.3,7.15,Asha,OK
41,2026-01-07 01:00,B1005,R3,78.1,5.13,12.25,88.8,7.24,Bimal,OK
42,2026-01-07 02:00,B1005,R1,78.8,5.19,12.36,89.4,6.70,Chen,OK
43,2026-01-07 03:00,B1005,R2,79.4,5.24,12.47,89.9,6.79,Deepa,OK
52,2026-01-07 12:00,B1006,R2,75.2,5.13,12.47,87.8,6.97,Asha,OK
53,2026-01-07 13:00,B1006,R3,75.8,5.19,12.58,88.3,7.06,Bimal,OK
54,2026-01-07 14:00,B1006,R1,76.5,5.24,11.70,88.8,7.15,Chen,OK
55,2026-01-07 15:00,B1006,R2,77.1,4.69,11.81,89.4,7.24,Deepa,OK
56,2026-01-07 16:00,B1006,R3,77.7,4.75,11.92,89.9,6.70,Asha,NOT TAKEN
65,2026-01-08 01:00,B1007,R3,83.3,5.28,11.92,87.8,6.88,Bimal,OK
66,2026-01-08 02:00,B1007,R1,83.9,4.73,12.03,88.3,6.97,Chen,OK
67,2026-01-08 03:00,B1007,R2,84.5,4.79,12.14,88.8,7.06,Deepa,OK
68,2026-01-08 04:00,B1007,R3,74.6,4.84,12.25,89.4,7.15,Asha,OK
69,2026-01-08 05:00,B1007,R1,75.2,4.90,12.36,89.9,7.24,Bimal,OK
78,2026-01-08 14:00,B1008,R1,81.6,4.79,12.36,87.8,6.79,Chen,OK
79,2026-01-08 15:00,B1008,R2,82.2,4.84,12.47,88.3,6.88,Deepa,OK
80,2026-01-08 16:00,B1009,R3,82.8,4.90,12.58,89.1,6.97,Asha,OK
81,2026-01-08 17:00,B1009,R1,83.5,4.95,11.70,89.7,7.06,Bimal,OK
91,2026-01-09 03:00,B1010,R2,79.1,4.94,11.81,88.1,6.70,Deepa,OK
92,2026-01-09 04:00,B1010,R3,79.7,4.99,11.92,88.6,6.79,Asha,OK
93,2026-01-09 05:00,B1010,R1,80.4,5.05,12.03,89.1,6.88,Bimal,OK
94,2026-01-09 06:00,B1010,R2,81.0,5.10,12.14,89.7,6.97,Chen,OK

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
84,2026-01-08 20:00,B1009,R1,85.3,5.12,12.03,91.2,6.7,Asha,OK

**Try it (5 min):** Filter batches operated by `Bimal`. Then filter all batches with conversion at least 90%.

**Challenge:** Use `.isin(['Asha', 'Chen'])` to select batches run by either operator.

## 4. Summaries by group (12 min)

`groupby()` asks the same question for each category. Here we compare average conversion and temperature by reactor. A group average is a clue to investigate, not proof of cause and effect.

In [7]:
reactor_summary = batches.groupby('reactor')[['temperature_c', 'conversion_percent']].mean()
display(reactor_summary)

operator_summary = batches.groupby('operator')['conversion_percent'].agg(['count', 'mean', 'min', 'max'])
display(operator_summary)

         temperature_c  conversion_percent
reactor
R1           79.158824           90.808824
R2           79.015152           90.678788
R3           79.021212           90.796970

          count    mean   min   max
operator
Asha         25  90.792  87.5  94.0
Bimal        25  90.772  87.5  94.0
Chen         25  90.752  87.5  94.3
Deepa        25  90.732  87.5  94.0

## Practical task: investigation shortlist (12 min)

Create a shortlist of batches that have conversion below 90% **or** temperature above 90 °C. Show only `batch_id`, `reactor`, temperature, and conversion; sort it by conversion.

**Challenge:** Add a `status` column with `REVIEW` for conversion below 90% and `OK` otherwise. Do not modify `batches`; work on a copy.

In [18]:
# Your investigation shortlist
r1_batches = batches[batches['reactor'] == 'R1']
low_conversion = batches[batches['conversion_percent'] < 90]
hot_and_low = batches[(batches['temperature_c'] > 90) | (batches['conversion_percent'] < 90)]


display(r1_batches)
display(low_conversion)
display(hot_and_low)

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
6,2026-01-05 14:00,B1001,R1,76.7,4.98,12.36,90.6,7.24,Chen,OK
9,2026-01-05 17:00,B1001,R1,78.6,5.15,11.70,92.2,6.88,Bimal,OK
12,2026-01-05 20:00,B1002,R1,80.4,4.71,12.03,93.7,7.15,Asha,OK
15,2026-01-05 23:00,B1002,R1,82.3,4.87,12.36,88.5,6.79,Deepa,OK
18,2026-01-06 02:00,B1002,R1,73.6,5.04,11.70,90.1,7.06,Chen,OK
21,2026-01-06 05:00,B1003,R1,75.5,5.20,12.03,91.7,6.70,Bimal,OK
24,2026-01-06 08:00,B1003,R1,77.3,4.76,12.36,93.2,6.97,Asha,OK
27,2026-01-06 11:00,B1003,R1,80.0,4.93,11.70,88.0,7.24,Deepa,OK
30,2026-01-06 14:00,B1004,R1,81.9,5.13,12.03,89.6,6.88,Chen,OK
33,2026-01-06 17:00,B1004,R1,83.7,4.69,12.36,91.1,7.15,Bimal,OK
36,2026-01-06 20:00,B1004,R1,75.0,4.86,11.70,92.7,6.79,Asha,OK
39,2026-01-06 23:00,B1004,R1,76.9,5.02,12.03,87.5,7.06,Deepa,OK
42,2026-01-07 02:00,B1005,R1,78.8,5.19,12.36,89.4,6.70,Chen,OK
45,2026-01-07 05:00,B1005,R1,80.6,4.75,11.70,90.9,6.97,Bimal,OK
48,2026-01-07 08:00,B1005,R1,82.5,4.91,12.03,92.5,7.24,Asha,OK
51,2026-01-07 11:00,B1006,R1,74.6,5.08,12.36,94.0,6.88,Deepa,OK
54,2026-01-07 14:00,B1006,R1,76.5,5.24,11.70,88.8,7.15,Chen,OK
57,2026-01-07 17:00,B1006,R1,78.3,4.80,12.03,90.4,6.79,Bimal,OK
60,2026-01-07 20:00,B1007,R1,80.2,5.01,12.36,92.0,7.06,Asha,OK
63,2026-01-07 23:00,B1007,R1,82.0,5.17,11.70,93.5,6.70,Deepa,OK
66,2026-01-08 02:00,B1007,R1,83.9,4.73,12.03,88.3,6.97,Chen,OK
69,2026-01-08 05:00,B1007,R1,75.2,4.90,12.36,89.9,7.24,Bimal,OK
72,2026-01-08 08:00,B1008,R1,77.1,5.06,11.70,91.4,6.88,Asha,OK
75,2026-01-08 11:00,B1008,R1,79.7,5.23,12.03,93.0,7.15,Deepa,OK
78,2026-01-08 14:00,B1008,R1,81.6,4.79,12.36,87.8,6.79,Chen,OK
81,2026-01-08 17:00,B1009,R1,83.5,4.95,11.70,89.7,7.06,Bimal,OK
84,2026-01-08 20:00,B1009,R1,85.3,5.12,12.03,91.2,6.70,Asha,OK
87,2026-01-08 23:00,B1009,R1,76.6,5.28,12.36,92.8,6.97,Deepa,OK
90,2026-01-09 02:00,B1010,R1,78.5,4.88,11.70,94.3,7.24,Chen,OK
93,2026-01-09 05:00,B1010,R1,80.4,5.05,12.03,89.1,6.88,Bimal,OK
96,2026-01-09 08:00,B1010,R1,82.2,5.21,12.36,90.7,7.15,Asha,OK
99,2026-01-09 11:00,B1010,R1,84.1,4.77,11.70,92.3,6.79,Deepa,OK

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
1,2026-01-05 09:00,B1001,R2,73.6,4.71,11.81,88.0,6.79,Bimal,OK
2,2026-01-05 10:00,B1001,R3,74.2,4.76,11.92,88.5,6.88,Chen,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
4,2026-01-05 12:00,B1001,R2,75.5,4.87,12.14,89.6,7.06,Asha,OK
13,2026-01-05 21:00,B1002,R2,81.1,4.76,12.14,87.5,7.24,Bimal,OK
14,2026-01-05 22:00,B1002,R3,81.7,4.82,12.25,88.0,6.70,Chen,OK
15,2026-01-05 23:00,B1002,R1,82.3,4.87,12.36,88.5,6.79,Deepa,OK
16,2026-01-06 00:00,B1002,R2,82.9,4.93,12.47,89.1,6.88,Asha,OK
17,2026-01-06 01:00,B1002,R3,73.0,4.98,12.58,89.6,6.97,Bimal,NOT TAKEN
26,2026-01-06 10:00,B1003,R3,79.4,4.87,12.58,87.5,7.15,Chen,OK
27,2026-01-06 11:00,B1003,R1,80.0,4.93,11.70,88.0,7.24,Deepa,OK
28,2026-01-06 12:00,B1003,R2,80.6,4.98,11.81,88.5,6.70,Asha,OK
29,2026-01-06 13:00,B1003,R3,81.2,5.04,11.92,89.1,6.79,Bimal,OK
30,2026-01-06 14:00,B1004,R1,81.9,5.13,12.03,89.6,6.88,Chen,OK
39,2026-01-06 23:00,B1004,R1,76.9,5.02,12.03,87.5,7.06,Deepa,OK
40,2026-01-07 00:00,B1005,R2,77.5,5.08,12.14,88.3,7.15,Asha,OK
41,2026-01-07 01:00,B1005,R3,78.1,5.13,12.25,88.8,7.24,Bimal,OK
42,2026-01-07 02:00,B1005,R1,78.8,5.19,12.36,89.4,6.70,Chen,OK
43,2026-01-07 03:00,B1005,R2,79.4,5.24,12.47,89.9,6.79,Deepa,OK
52,2026-01-07 12:00,B1006,R2,75.2,5.13,12.47,87.8,6.97,Asha,OK
53,2026-01-07 13:00,B1006,R3,75.8,5.19,12.58,88.3,7.06,Bimal,OK
54,2026-01-07 14:00,B1006,R1,76.5,5.24,11.70,88.8,7.15,Chen,OK
55,2026-01-07 15:00,B1006,R2,77.1,4.69,11.81,89.4,7.24,Deepa,OK
56,2026-01-07 16:00,B1006,R3,77.7,4.75,11.92,89.9,6.70,Asha,NOT TAKEN
65,2026-01-08 01:00,B1007,R3,83.3,5.28,11.92,87.8,6.88,Bimal,OK
66,2026-01-08 02:00,B1007,R1,83.9,4.73,12.03,88.3,6.97,Chen,OK
67,2026-01-08 03:00,B1007,R2,84.5,4.79,12.14,88.8,7.06,Deepa,OK
68,2026-01-08 04:00,B1007,R3,74.6,4.84,12.25,89.4,7.15,Asha,OK
69,2026-01-08 05:00,B1007,R1,75.2,4.90,12.36,89.9,7.24,Bimal,OK
78,2026-01-08 14:00,B1008,R1,81.6,4.79,12.36,87.8,6.79,Chen,OK
79,2026-01-08 15:00,B1008,R2,82.2,4.84,12.47,88.3,6.88,Deepa,OK
80,2026-01-08 16:00,B1009,R3,82.8,4.90,12.58,89.1,6.97,Asha,OK
81,2026-01-08 17:00,B1009,R1,83.5,4.95,11.70,89.7,7.06,Bimal,OK
91,2026-01-09 03:00,B1010,R2,79.1,4.94,11.81,88.1,6.70,Deepa,OK
92,2026-01-09 04:00,B1010,R3,79.7,4.99,11.92,88.6,6.79,Asha,OK
93,2026-01-09 05:00,B1010,R1,80.4,5.05,12.03,89.1,6.88,Bimal,OK
94,2026-01-09 06:00,B1010,R2,81.0,5.10,12.14,89.7,6.97,Chen,OK

,timestamp,batch_id,reactor,temperature_c,pressure_bar,flow_m3_h,conversion_percent,ph,operator,sample_status
0,2026-01-05 08:00,B1001,R1,73.0,4.65,11.70,87.5,6.70,Asha,OK
1,2026-01-05 09:00,B1001,R2,73.6,4.71,11.81,88.0,6.79,Bimal,OK
2,2026-01-05 10:00,B1001,R3,74.2,4.76,11.92,88.5,6.88,Chen,OK
3,2026-01-05 11:00,B1001,R1,74.9,4.82,12.03,89.1,6.97,Deepa,OK
4,2026-01-05 12:00,B1001,R2,75.5,4.87,12.14,89.6,7.06,Asha,OK
13,2026-01-05 21:00,B1002,R2,81.1,4.76,12.14,87.5,7.24,Bimal,OK
14,2026-01-05 22:00,B1002,R3,81.7,4.82,12.25,88.0,6.70,Chen,OK
15,2026-01-05 23:00,B1002,R1,82.3,4.87,12.36,88.5,6.79,Deepa,OK
16,2026-01-06 00:00,B1002,R2,82.9,4.93,12.47,89.1,6.88,Asha,OK
17,2026-01-06 01:00,B1002,R3,73.0,4.98,12.58,89.6,6.97,Bimal,NOT TAKEN
26,2026-01-06 10:00,B1003,R3,79.4,4.87,12.58,87.5,7.15,Chen,OK
27,2026-01-06 11:00,B1003,R1,80.0,4.93,11.70,88.0,7.24,Deepa,OK
28,2026-01-06 12:00,B1003,R2,80.6,4.98,11.81,88.5,6.70,Asha,OK
29,2026-01-06 13:00,B1003,R3,81.2,5.04,11.92,89.1,6.79,Bimal,OK
30,2026-01-06 14:00,B1004,R1,81.9,5.13,12.03,89.6,6.88,Chen,OK
39,2026-01-06 23:00,B1004,R1,76.9,5.02,12.03,87.5,7.06,Deepa,OK
40,2026-01-07 00:00,B1005,R2,77.5,5.08,12.14,88.3,7.15,Asha,OK
41,2026-01-07 01:00,B1005,R3,78.1,5.13,12.25,88.8,7.24,Bimal,OK
42,2026-01-07 02:00,B1005,R1,78.8,5.19,12.36,89.4,6.70,Chen,OK
43,2026-01-07 03:00,B1005,R2,79.4,5.24,12.47,89.9,6.79,Deepa,OK
52,2026-01-07 12:00,B1006,R2,75.2,5.13,12.47,87.8,6.97,Asha,OK
53,2026-01-07 13:00,B1006,R3,75.8,5.19,12.58,88.3,7.06,Bimal,OK
54,2026-01-07 14:00,B1006,R1,76.5,5.24,11.70,88.8,7.15,Chen,OK
55,2026-01-07 15:00,B1006,R2,77.1,4.69,11.81,89.4,7.24,Deepa,OK
56,2026-01-07 16:00,B1006,R3,77.7,4.75,11.92,89.9,6.70,Asha,NOT TAKEN
65,2026-01-08 01:00,B1007,R3,83.3,5.28,11.92,87.8,6.88,Bimal,OK
66,2026-01-08 02:00,B1007,R1,83.9,4.73,12.03,88.3,6.97,Chen,OK
67,2026-01-08 03:00,B1007,R2,84.5,4.79,12.14,88.8,7.06,Deepa,OK
68,2026-01-08 04:00,B1007,R3,74.6,4.84,12.25,89.4,7.15,Asha,OK
69,2026-01-08 05:00,B1007,R1,75.2,4.90,12.36,89.9,7.24,Bimal,OK
78,2026-01-08 14:00,B1008,R1,81.6,4.79,12.36,87.8,6.79,Chen,OK
79,2026-01-08 15:00,B1008,R2,82.2,4.84,12.47,88.3,6.88,Deepa,OK
80,2026-01-08 16:00,B1009,R3,82.8,4.90,12.58,89.1,6.97,Asha,OK
81,2026-01-08 17:00,B1009,R1,83.5,4.95,11.70,89.7,7.06,Bimal,OK
91,2026-01-09 03:00,B1010,R2,79.1,4.94,11.81,88.1,6.70,Deepa,OK
92,2026-01-09 04:00,B1010,R3,79.7,4.99,11.92,88.6,6.79,Asha,OK
93,2026-01-09 05:00,B1010,R1,80.4,5.05,12.03,89.1,6.88,Bimal,OK
94,2026-01-09 06:00,B1010,R2,81.0,5.10,12.14,89.7,6.97,Chen,OK

## Exit check

You can sort a DataFrame, filter with one or more conditions, and use `groupby` for transparent summaries. Next: use charts to communicate patterns.